### ISSUE TITLE
Extension formatting broken on Apple Silicon macs

### ISSUE THREAD

**Issue by bodhiwd** [gildas-lormeau/JSONVue#100]
Formatting and functionality seems to be almost completely broken on Apple Silicon Macs, see:
<img width="768" alt="Screenshot 2022-07-11 at 12 05 50" src="https://user-images.githubusercontent.com/48051498/178229164-d6b1aec8-c307-427e-a2ab-2d007153a51c.png">

Also reported on support page for the Extension: https://chrome.google.com/webstore/detail/jsonvue/chklaanhfefbnpoihckbnefhakgolnmc

**Comment by gildas-lormeau** [comment]
I don't own a Mac but it looks like it's a bug in Chrome.

**Comment by bhavyasaggi-housing** [comment]
Faced with similiar issue, and it resolved by opening:
Extensions > JSONVue > Extension Options > Open the Style Editor
On `chrome-extension://***/css-editor.html`, and then everything started working upon pressing 'Reset'.

**Comment by bodhiwd** [comment]
> Faced with similiar issue, and it resolved by opening: Extensions > JSONVue > Extension Options > Open the Style Editor On `chrome-extension://***/css-editor.html`, and then everything started working upon pressing 'Reset'.

🙏  Awesome, can also reproduce the fix. Just need to save afterwards and reload the HTTP request 🎉

**Comment by gildas-lormeau** [comment]
If I'm not wrong, this issue was fixed. Feel free to reopen it if necessary.
