### ISSUE TITLE
Extension is broken with chrome 117

### ISSUE THREAD

**Issue by doranych** [gildas-lormeau/JSONVue#106]
Something changed in chrome v117 , previously in v116, the json would just be rendered. 

Now in v117 it requires me to click pretty print. 

Pretty print button uses native language, which makes me think that extension is completely broken

**Comment by gildas-lormeau** [comment]
The new version has been published on the store.

**Comment by gildas-lormeau** [comment]
There's also unfortunately a minor document margin issue in the version 0.2.0. It's fixed in the version 0.2.1.

**Comment by doranych** [comment]
it works for me
thx

**Comment by gildas-lormeau** [comment]
You're welcome :)

**Comment by minipeach** [comment]
Thanks for adapting in chrome v117 ，This is the best json formatter for chrome， I like it
