### ISSUE TITLE
improper integer rounding

### ISSUE THREAD

**Issue by lowang** [gildas-lormeau/JSONVue#11]
My json contains 64bit ids and jsonview is rounding them causing mass confusion. So in example below 2916334247900527532 is rounded to 2916334247900527600

JSON:
{"total":1,"limit":25,"offset":0,"query_time":17,"http_time":0.0260000228881836,"rows":[{"id":2916334247900527532,"title":"LENOVO IdeaPad S10-3t","description":"Notebook z ekranem o przek\u0105tnej 10.1","price_min":1425.99,"price_max":1722.21,"offer_count":23,"shop_count":23,"category_id":10901,"product_type_id":2331,"source":"bdk","source_id":516188,"is_with_photo":"y","photo_id":"332d22eb688516883e0512828b6aba47","offer_id":null,"url_original":null,"offer_shop_id":null,"shop_name":null,"shop_url":null,"top_category_id":10901,"top_position":14,"click_value":0.0,"title_normalized":"lenovoideapads103t"}],"enrichment_time":0.0400002002716064}

**Comment by drdamour** [comment]
+1

**Comment by gildas-lormeau** [comment]
This issue is due to the fact that the extension relies on `JSON.parse` to extract the JS data.

**Comment by gildas-lormeau** [comment]
This issue will be fixed in the version 0.1.17 by enabling the option "Support 64-bit signed integers".
