### ISSUE TITLE
mimetype: application/{datatype}+json

### ISSUE THREAD

**Issue by zuperglue** [gildas-lormeau/JSONVue#12]
Would it be possible to suport responses that uses mimetype notation "application/{datatype}+json" aswell? A lot of REST API is using this markup.

**Comment by itsravenous** [comment]
+1 we're implementing several custom media types for our web app and this would be really useful for members of our team who use Chrome. The Firefox plugin on which this is based has a field in the options page to drop additional mime types in.

**Comment by DrGirlfriend** [comment]
With Scene7/CQ/AOD (Adobe) JSONP requests use the mimetype due to security team mandates text/javascript;charset=UTF-8

These requests currently are not processed by this plugin

**Comment by gildas-lormeau** [comment]
The extension does not check the mimetype of the content, because it cannot (without additional permissions).

**Comment by cowwoc** [comment]
@gildas-lormeau Why not ask for additional permissions?
