### ISSUE TITLE
Strings in local JSON not decoded correctly 

### ISSUE THREAD

**Issue by ghost** [gildas-lormeau/JSONVue#15]
Per the JSON spec, a JSON file is in one of UTF-8, UTF-16LE, UTF-16BE, UTF-32LE or UTF-32BE and the question of which is determined by examining the pattern of 00 bytes at the start of the document.

My JSON files are in UTF-8 and contain strings such as:

"• Upper"

the bullet is encoded as the 3-byte sequence 0xe2, 0x80, 0xa2. This is rendered as "â€¢ Upper" in JSONView for Chrome when the file is loaded from my local machine.

Also affected are the currency symbols in prices:

"£6.00"

the pound symbol is encoded as the 2-byte sequence 0xc2, 0xa3 is rendered as "Â£6.00".

We could re-write our JSON generator to encode everything outside the 7-bit clean area as a \u escape sequence but we'd really rather not.

**Comment by gildas-lormeau** [comment]
AFAIK, this cannot be fixed. This is a bug in the browser.
