### ISSUE TITLE
ignore json vulnerability prefix )]}',

### ISSUE THREAD

**Issue by arkarkark** [gildas-lormeau/JSONVue#21]
if you look at JSON vulnerability here:
http://docs.angularjs.org/api/ng.$http

you see some websites will prefix their json output with
)]}',\n

it'd be super neat if JSONView ignore that if it was at the start of a reply.

**Comment by AncientSwordRage** [comment]
:+1:

**Comment by H3llK33p3r** [comment]
Please integrate pull request : https://github.com/gildas-lormeau/JSONView-for-Chrome/pull/22 :) !
