### ISSUE TITLE
Bug: Nested objects in JSON get improperly HTML symbols parsed

### ISSUE THREAD

**Issue by PanMan** [gildas-lormeau/JSONVue#24]
It took me an hour to figure out this is not a bug in my backend, but in the Jsonviewer. This is the minimal example I could find. This json:
    {"data":"http:\/\/panman.nl?a=b&currencyCode=EUR"}

This shows a link to "http://panman.nl?a=b¤cyCode=EUR" . Notice the strange symbol after a=b.
The &curren gets treated as a HTML symbol, while it doesn't have the (needed) semicolon:
&curren; is a html symbol, &curren without the semicolon is nothing. Regardles if the JSON viewer should show HTML encoded symbols.

**Comment by gildas-lormeau** [comment]
I could not reproduce the issue.
