### ISSUE TITLE
Can't handle large integer values

### ISSUE THREAD

**Issue by Eyjafjallajokull** [gildas-lormeau/JSONVue#27]
Example JSON document:

``` json
{"total":6463978,"limit":1,"offset":0,"times":{"query_time":1535,"http_time":1.546,"enrichment_time":0.007},"rows":[{"id":2272963852315277554}]}
```

JsonView will display wrong ID - instead of 2272963852315277554 it will be 2272963852315277600

**Comment by gildas-lormeau** [comment]
This issue will be fixed in the version 0.1.17 by enabling the option "Support 64-bit signed integers".
