### ISSUE TITLE
Floating point numbers incorrectly converted to integers

### ISSUE THREAD

**Issue by paulschreiber** [gildas-lormeau/JSONVue#40]
Floating point numbers ending in .0  are incorrectly converted to integers:

Example:

```
{
  "4": {
    "name": "Hello",
    "vorb": 14.0
  },
  "5": {
    "name": "Goodbye",
    "vorb": 15
  },
  "6": {
    "name": "Tacos",
    "vorb": 15.1
 }
}
```

![jsonview](https://cloud.githubusercontent.com/assets/86784/3233517/067ea810-f0bf-11e3-989e-00fc91761a1a.png)

**Comment by lsloan** [comment]
The Firefox version of JSONView 1.1.1 does **not** have this problem.

https://addons.mozilla.org/en-us/firefox/addon/jsonview/

**Comment by gildas-lormeau** [comment]
The data displayed in the browser is a JavaScript object, so it's converted to a Number.

**Comment by lsloan** [comment]
There's no disagreement that the values are numbers.  The problem is that a floating point "14.0" is being displayed as an integer "14".

**Comment by gildas-lormeau** [comment]
Then, they should use another extension maybe. The goal of this one is to display JSON string as JavaScript objects.
