### ISSUE TITLE
Copy path / value doesn't work on non-toplevel elements

### ISSUE THREAD

**Issue by gaborkr** [gildas-lormeau/JSONVue#58]
If I try to "copy path" / "copy value" of a non-top level part of a JSON structure I get the value of the last successful copy operation or the text "undefined" in the clipboard.

This is on Ubuntu 15.04, Chrome 44.

Example: given the following file:
`{
"toplevel": {
    "doesn't work": "try to copy me"
    }
}`

trying to copy the inner `{"doesn't work":"try to copy me"}` block won't put anything on the clipboard.

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue.

**Comment by gildas-lormeau** [comment]
I was able to reproduce the issue, it will be fixed in the version 0.1.12+.
