### ISSUE TITLE
need collapse all

### ISSUE THREAD

**Issue by pstanton** [gildas-lormeau/JSONVue#63]
if i'm looking for one field in a tree, i don't want every field expanded by default.

**Comment by AhmedKamal20** [comment]
There is "collapse all" Option , in the top right of the screen
![screenshot 38](https://cloud.githubusercontent.com/assets/14352372/17481062/49425ae0-5d7b-11e6-8737-3f534e385841.png)

**Comment by roundar** [comment]
I was going to submit the same issue or look at contributing.  Any interest in making it a little more intuitive?  The context menu is the first place I tried to look.
