### ISSUE TITLE
Newline characters are not rendered properly as HTML

### ISSUE THREAD

**Issue by stewx** [gildas-lormeau/JSONVue#66]
The sequence "\n" is not being rendered correctly.

A string like "Hello\nJSON\nworld!" is rendered as the HTML

```
    <span class="type-string">"Hello
    JSON
    world!"</span>
```

(The newlines here are totally ignored by browsers since this is all within a single block element)

It should be rendered to HTML like:

`<span class="type-string">"Hello\nJSON\nworld!"</span>`

**Comment by gildas-lormeau** [comment]
it will be fixed in the next version
