### ISSUE TITLE
Update with features from original Firefox extension

### ISSUE THREAD

**Issue by lsloan** [gildas-lormeau/JSONVue#67]
Many issues mentioned in this repository do not exist in the original Firefox version of JSONView.  They've either been fixed already or were never a problem for that version.  The FF version also has several additional features that this one does not.

**_Please_** update this repository and the extension in the Chrome Web Store to include the fixes and features from the Firefox extension.

Thank you!

**Comment by rcn46** [comment]
@

> #90
