### ISSUE TITLE
JSONView not letting a page render when its URL has .json in the end and response is HTML.

### ISSUE THREAD

**Issue by madhurahuja** [gildas-lormeau/JSONVue#69]
NPM JS [using a package documentation page](https://docs.npmjs.com/getting-started/using-a-package.json) does not work when JSONView extension is enabled.

For reference-
https://github.com/npm/docs/issues/722

**Comment by gildas-lormeau** [comment]
This issue cannot be fixed AFAIK because there is no generic way to find the JSON contents in the page.
