### ISSUE TITLE
Can you add support for json5

### ISSUE THREAD

**Issue by pjangam** [gildas-lormeau/JSONVue#71]
I really love your plugin and it has really been helpfull while working on json based REST apis.

[Json5](https://github.com/json5/json5) is json with some addded capabilities in it like inline comments.
I am using josn5 in one of my project. Chrome render fails when I try to open any of json5 document.
Can you add support for inline comments to your plugin. It will be really helpful.

Thanks!

**Comment by gildas-lormeau** [comment]
The extension relies on `JSON.parse` to extract the JS data so this feature cannot be implemented.
