### ISSUE TITLE
JSONView tries to parse Haskell source files.

### ISSUE THREAD

**Issue by phadej** [gildas-lormeau/JSONVue#79]
Obviously fails miserably: e.g. http://hackage.haskell.org/package/base-4.9.1.0/docs/src/GHC.Base.html#

![image](https://user-images.githubusercontent.com/51087/27229213-62e55a6e-52b3-11e7-8637-8d57feaf9522.png)

**Comment by sidvishnoi** [comment]
Needs a better JSON detection than this:
https://github.com/gildas-lormeau/JSONView-for-Chrome/blob/f0f7425c61ed102451fba42dba35cdfc58ae90e3/WebContent/content.js#L96

![image](https://user-images.githubusercontent.com/8426945/45960345-ac3abe80-c039-11e8-8266-f712aaa28a6d.png)

**Comment by aspiers** [comment]
I see it trying to parse `text/plain` log files too.

**Comment by aspiers** [comment]
OK, it wasn't hard to find out what's going wrong:

https://github.com/gildas-lormeau/JSONView-for-Chrome/blob/f0f7425c61ed102451fba42dba35cdfc58ae90e3/WebContent/content.js#L95-L97

You can see that it will assume any file wrapped in `[...]` or `{...}` parentheses is JSON, which is pretty naive.

**Comment by zhbaba** [comment]
什么鬼🤔




| |
张恒
|
|
邮箱：z7h777777@163.com
|

签名由 网易邮箱大师 定制

On 08/08/2019 02:55, Adam Spiers wrote:

OK, it wasn't hard to find out what's going wrong:

https://github.com/gildas-lormeau/JSONView-for-Chrome/blob/f0f7425c61ed102451fba42dba35cdfc58ae90e3/WebContent/content.js#L95-L97

You can see that it will assume any file wrapped in [...] or {...} parentheses is JSON, which is pretty naive.
