### ISSUE TITLE
Feature request: support JSON-Schema

### ISSUE THREAD

**Issue by barkermn01** [gildas-lormeau/JSONVue#84]
I use this plugin daily but i started working on a system that's using JSON-Schema and i would love it if JSONView could identify that and allow the "$ref" values to be linked to and use the path of $id if there is one E.G

```
{
	"$schema": "http://json-schema.org/schema#",
	"$id":"https://api.thisisbeacon.com/schemas/",
	"definitions":{
		"link":{
        	       "$ref":"link/"
		},
		"campaign":{
        	        "$ref":"campaign/"
		},
		"customer":{
			"$ref":"customer/"
		},
                "encryption":{
          	         "$ref":"link/post/single.schema.json"
                }
	}
}
```

So the in this i would like "> definitions > link > $ref" value to be linked from equating value of "> $id" concatinated with "> definitions > link > $ref" so it would show the text "link/" as the value but is clickable to link to "https://api.thisisbeacon.com/schemas/link/"

**Comment by gildas-lormeau** [comment]
I'm sorry but this is out of the scope.
