### ISSUE TITLE
Don't reorder key-value pairs

### ISSUE THREAD

**Issue by ploober** [gildas-lormeau/JSONVue#88]
I noticed that when I am displaying JSON using this plugin, my key-value (string to number) pairs were coming in out of order. It caused confusion because the particular map was sorted by the value so it was appearing out of order.

**Comment by CrazyTim** [comment]
Possible duplicate #80

**Comment by gildas-lormeau** [comment]
The extension relies on `JSON.parse` to extract the JS data, that's why keys are reordered.
