### ISSUE TITLE
query param to collapse all items by default

### ISSUE THREAD

**Issue by ORESoftware** [gildas-lormeau/JSONVue#89]
Is there some query param in the URL we can use, so it collapses all json objects by default?

So this is collapsed:

<kbd>
<img width="367" alt="Screen Shot 2019-07-02 at 2 15 32 PM" src="https://user-images.githubusercontent.com/11139560/60547176-ea08f980-9cd3-11e9-8879-bfbed48623f0.png">
</kbd>

<br>

----

is there a way to make that the default *or* to use some query param:

```
<url>:<port>?json_viewer_collapse_all=yes
```

**Comment by tmak7** [comment]
would really love to see an option to toggle the default behaviour so that the JSON data is collapsed by default

**Comment by gildas-lormeau** [comment]
This can now be achieved via the option `Maximum depth level of initially expanded elements`.
