### ISSUE TITLE
Display in monospace fonts

### ISSUE THREAD

**Issue by golopot** [gildas-lormeau/JSONVue#98]
I am used to read json in monospace fonts.

**Comment by gildas-lormeau** [comment]
You can customize the CSS via the options page.

**Comment by cawoodm** [comment]
Guys, monospace should be the default - nobody works like this:
![image](https://user-images.githubusercontent.com/498834/184337616-15816092-a1ef-4755-8a99-b1cc209104c8.png)

**Comment by gildas-lormeau** [comment]
This is the default, please reset your stylesheet via the CSS editor in the options page.

**Comment by cawoodm** [comment]
I know, I'm saying it's a bad default. Like delivering cups without a bottom, every user has to change it.

**Comment by gildas-lormeau** [comment]
I don't know what is causing this issue. AFAIK, it does not affect all the users.

**Comment by gildas-lormeau** [comment]
The bug is fixed in the version `0.1.18` I just uploaded on the store. It should be available for download in the coming days hopefully.
